"""project and machine tables

Revision ID: 89cb4bcfb800
Revises: 
Create Date: 2021-01-31 13:16:09.781695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cb4bcfb800'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobnum', sa.String(length=12), nullable=True),
    sa.Column('ec_date', sa.String(length=12), nullable=True),
    sa.Column('engineer', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serialnum', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_serialnum'), 'machine', ['serialnum'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_serialnum'), table_name='machine')
    op.drop_table('machine')
    op.drop_table('project')
    # ### end Alembic commands ###
